# Example input file

[Temporal]
input_path = '../../TEMPORAL/'
output_path = '../Figures'

[isoc]
input_path_int_res = '../../POST/integrate_iso_c/int_A_res*.csv'
input_path_int_tot = '../../POST/integrate_iso_c/int_A_tot*.csv'
input_path_int_norm_grac_c = '../../POST/integrate_gradc/integral_grad_c_*.csv'
input_path_stats = '../../POST/isoc_stats/isoc_stats_*.csv'
output_path = '../Figures'
